pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t alpine.'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker login --username=Msd967 --password=Msd@00112233'
                sh 'docker tag myimage Msd967/alpine'
                sh 'docker push Msd967/alpine'
            }
        }
    }
}
